backend:
  name: github
  repo: kernesgenaa-a11y/222
  branch: main
  base_url: https://sveltia-cms-auth.kernesgenaa.workers.dev/

media_folder: "images/uploads"
public_folder: "/images/uploads"

locale: 'uk'

collections:
  - name: "news"
    label: "Новини"
    folder: "data/news"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Заголовок", name: "title", widget: "string" }
      - { label: "Дата", name: "date", widget: "datetime" }
      - { label: "Автор", name: "author", widget: "string", default: "Дентіс" }
      - { label: "Категорія", name: "category", widget: "select", options: ["Поради щодо здоров'я", "Професійний розвиток", "Акції"] }      
      - { label: "Текст", name: "body", widget: "markdown" }


